code-differently/code-differently-24-q4

.devcontainer/devcontainer.json

feat: adds gh to devcontainer

---

.devcontainer/devcontainer.json

- **feat: adds gh to devcontainer (#49)**
- **feat: configured terminal profile for devcontainer**

feat: add terminal config in devcontainer

---

lesson_01/nilejackson/index.html

I removed the css color styling, and lined the margins/spacing up with my original README.md document.

Lesson 01/revision for nilejackson

---

.github/workflows/check_push.yml

fix: correct lesson 02 command

---

lesson_04/jimoye244/README.md

Java and Javascript were the languages used in the implementation of the prime number function. The function was implemented in such a way that it returns 'true' or 'false' depending on the number argument passed.

feat: two languages function implementation for HW04-Oyeyemi Jimoh

---

.github/workflows/check_lesson_06_pr.yaml
.github/workflows/check_push.yml

chore: adds lesson_06 checks

---

lesson_06/expression/src/expression_calculator.ts

Reverts code-differently/code-differently-24-q4#252

Revert "Pablo Limon-Paredes Lesson06, Expression Calculator"

---

.github/workflows/check_lesson_05_pr.yaml

chore: add lesson_05 quiz check

---

lesson_05/Pablo_limon_paredes_User_stories/README.md

These are the User stories two of which are real, the first and last one but the middle one I did make up a totally made up app.

Pablo Limon-Paredes 3 User stories Lesson_05

---

lesson_04/pablolimonparedes/README.md

I have here the coding and explanation as well as differences and similarities of Java and Python

Pablo Limon-Paredes Lesson 04 Prime number coding, Java and Python implementation

---

lesson_09/README.md

chore: add lesson_09 additional video

---

README.md

chore: restore readme

---

lesson_08/README.md
lesson_09/README.md

fix: updates links in lesson_08 and lesson_09

---

lesson_10/libraries/src/loaders/anthony_mays_loader.ts
lesson_10/libraries/src/models/credit.ts

chore: changes credit model to proper class

---

lesson_09/types/types_app/src/main/java/com/codedifferently/lesson9/dataprovider/JosephCaballeroProvider.java
lesson_09/types/types_app/src/main/resources/data/josephcaballero.json

Added personalized Provider Test and .json file for lesson_09

feat: Added personalized Provider Test and .json file for lesson_09 (Joseph Caballero)

---

lesson_10/libraries/src/lesson10.test.ts
lesson_10/libraries/src/models/credit.ts
lesson_10/libraries/src/models/media_collection.ts

- **chore: updates test to better reflect requirements**
- **chore: refactors media collection class**

chore: updates test to better reflect requirements

---

lesson_11/README.md

chore: clarifies video pre-work details

---

lesson_10/libraries/src/loaders/loaders.module.ts
lesson_10/libraries/src/loaders/nile_jackson_loader.ts

I have added changes to changes to the loader.ts and loader.module.ts files.

Feat:Adds Nile_Jackson_loader.ts and Modifies loader.ts -lesson10Hw

---

lesson_09/types/types_app/src/main/java/com/codedifferently/lesson9/dataprovider/NileJacksonProvider.java
lesson_09/types/types_app/src/main/resources/data/nilejack.json

Feat: Fix/Chore; Resubmitting lesson_09 HomeWork(Removed lesson_07 file).

Feat:Adds Lesson_09 Provider.java and JSON files for Nile Jackson

---

lesson_12/structs_ts/src/stack.test.ts

tests: added stack unit tests

---

lesson_12/structs_ts/src/list_node.ts

lint: remove lint error in list_node

---

lesson_10/libraries/src/loaders/james_capparell_loader.ts
lesson_10/libraries/src/loaders/loaders.module.ts

Extra Credit for lesson_10 homework

feat: combined credits with the media items by modifying the loadData method - James Capparell

---

lesson_09/types/types_app/src/main/java/com/codedifferently/lesson9/dataprovider/DavidSmithProvider.java
lesson_09/types/types_app/src/main/resources/data/davidsmith.json

Adds DavidSmithProvider.java and davidsmith.json for lesson 09 homework

feat:adds David Smith Lesson09 "davidsmith.json"

---

lesson_10/libraries/src/loaders/loaders.module.ts

fix: correcting bad merge

---

lesson_13/maps_java/maps_app/build.gradle.kts
lesson_14/exceptions/exceptions_app/build.gradle.kts
lesson_14/exceptions/exceptions_app/src/main/java/com/codedifferently/lesson14/ecommerce/EcommerceSystem.java
lesson_14/exceptions/exceptions_app/src/main/java/com/codedifferently/lesson14/ecommerce/ProductNotFoundException.java
lesson_14/exceptions/exceptions_app/src/test/java/com/codedifferently/lesson14/ecommerce/EcommerceSystemTest.java

fix: updates build config and adjust tests

---

lesson_13/maps_java/maps_app/build.gradle.kts
lesson_14/exceptions/exceptions_app/build.gradle.kts
lesson_14/exceptions/exceptions_app/src/main/java/com/codedifferently/lesson14/ecommerce/EcommerceSystem.java
lesson_14/exceptions/exceptions_app/src/main/java/com/codedifferently/lesson14/ecommerce/ProductNotFoundException.java
lesson_14/exceptions/exceptions_app/src/test/java/com/codedifferently/lesson14/ecommerce/EcommerceSystemTest.java

Reverts code-differently/code-differently-24-q4#458

Revert "fix: updates build config and adjust tests"

---

lesson_15/tdd/tdd_app/src/test/java/com/codedifferently/lesson15/Lesson15Test.java

tests: add more coverage for Lesson15

---

lesson_17/bank/bank_app/build.gradle.kts
lesson_17/bank/bank_app/src/test/java/com/codedifferently/lesson17/Lesson17Test.java
lesson_17/bank/settings.gradle.kts

tests: add more coverage

---

lesson_17/README.md
project_oop/README.md

feat: adds project_oop docs

---

.github/workflows/check_push.yml

chore: updating build checks

---

project_oop/README.md

docs: fixes minor nits and clarifications

---

project_oop/README.md

docs: adjusts dates

---

lesson_16/objects/objects_app/build.gradle.kts

- **docs: adjusts dates**
- **chore: fix lombok config**

chore: update lombok config

---

lesson_16/objects/objects_app/build.gradle.kts
lesson_17/README.md

- **chore: fix lombok config**
- **chore: update lesson 17 requirements**

docs: update lesson_17 hw requirements

---

lesson_17/bank/bank_app/build.gradle.kts

- **chore: fix lombok config**
- **chore: update lesson 17 requirements**
- **chore: adds proper lombok support**

chore: adds proper lombok support for L17

---

lesson_25/template/package-lock.json
lesson_25/template/package.json

chore: fix deps for lesson_25

---

lesson_25/template/vite.config.ts

fix: updates default host ip for vite

---

lesson_26/README.md

docs: adds instructions for typescript api

---

lesson_26/api/java/api_app/src/main/java/com/codedifferently/lesson26/web/MediaItemRequest.java

fix: changes how media item type is parsed

---

lesson_27/README.md

chore: adds prework for lesson_27

---

lesson_27/api/src/server.ts
lesson_27/template/vite.config.ts

- **chore: add server host binding for template**
- **fix: actually adds valid responses for the api**
- **fix: corrects file path to json file.**

fix: updates server to resolve issues with create api

---

lesson_27/api/jest.config.js
lesson_27/api/package-lock.json
lesson_27/api/package.json
lesson_27/api/src/data/programs.json
lesson_27/api/src/db.ts
lesson_27/api/src/index.ts
lesson_27/api/src/server.e2e.spec.ts
lesson_27/api/src/server.ts
lesson_27/api/tsconfig.json
lesson_27/template/package-lock.json
lesson_27/template/package.json

- **fix: actually adds valid responses for the api**
- **fix: corrects file path to json file.**
- **tests: adds basic e2e tests for server**
- **tests: adds jest config**
- **tests: refactored data access and completed tests**
- **chore: update jest config**
- **chore: properly configure types library**
- **chore: add types library**
- **chore: add prettier fix**

tests: increases testability and coverage for api server

---

capstone/README.md

feat: adds capstone requirements

---

capstone/README.md

chore: adds more requirements and v0 resource

---

lib/java/fullstack_demo/src/main/frontend/.env.development
lib/java/fullstack_demo/src/main/frontend/.env.production
lib/java/fullstack_demo/src/main/frontend/package.json

chore: fixes config for java

---

lesson_11/arrays_ts/package-lock.json

fix: syncs package-lock.json properly

---

lesson_12/structs_ts/package-lock.json
lesson_13/maps_ts/package-lock.json
lesson_27/template/package-lock.json

fix: updates package-lock.json for outdated projects

---

.github/workflows/check_push.yml
lib/typescript/fullstack_demo/README.md
lib/typescript/fullstack_demo/tailwind.config.ts

chore: adds push checks for fullstack demos

---

.github/workflows/check_push.yml

chore: fix actions commands

---

lib/java/fullstack_demo/src/main/resources/application.yml
lib/typescript/fullstack_demo/tsconfig.json

chore: minor adjustments to test gh actions

---

.github/workflows/check_fullstack_demo_java_pr.yaml
.github/workflows/check_fullstack_demo_ts_pr.yaml
.github/workflows/check_push.yml

- **chore: adds more build checks**
- **chore: adds pr checks for fullstack demos.**
- **chore: ensures actions run when config is modded**
- **chore: adds env variables for build**
- **chore: fix build action**
- **chore: tries to fix env vars**
- **chore: tries to fix env vars**

chore: fixes build actions

---

.github/workflows/check_push.yml

chore: fix push actions

---

syllabus/README.md

- **docs: updating syllabus with links to lessons**
- **docs: update link**

docs: update syllabus with links to lessons

---

slides/index.html

chore: replaces all title slides

---

lesson_00/README.md
lesson_01/README.md
lesson_02/README.md
lesson_03/README.md
lesson_04/README.md
lesson_05/README.md
lesson_06/README.md
lesson_07/README.md
lesson_08/README.md
lesson_09/README.md
lesson_10/README.md
lesson_11/README.md
lesson_12/README.md
lesson_13/README.md
lesson_14/README.md
lesson_15/README.md
lesson_16/README.md
lesson_17/README.md
lesson_21/README.md
lesson_22/README.md
lesson_23/README.md
lesson_24/README.md
lesson_25/README.md
lesson_26/README.md
lesson_27/README.md
lesson_28/README.md

fix: slides links

---

slides/css/theme/source/ml.scss
slides/dist/theme/ml.css
slides/index.html

chore: converts lesson_00 slides

---

slides/src/App.js

chore: configure preso options

---

supplemental_1/README.md

chore: adds next steps for supplemental lesson

---

lib/javascript/fullstack_demo/package.json

chore: add postinstall script for prisma

---

lib/javascript/fullstack_demo/package-lock.json
lib/javascript/fullstack_demo/package.json
lib/javascript/fullstack_demo/src/repositories/fakes/fake-prima-client.ts
lib/javascript/fullstack_demo/src/repositories/index.ts
lib/javascript/fullstack_demo/src/repositories/json-todo-repository.ts
lib/javascript/fullstack_demo/src/repositories/postgres-todo-repository.spec.ts
lib/javascript/fullstack_demo/src/repositories/postgres-todo-repository.ts
lib/javascript/fullstack_demo/src/repositories/redis-todo-repository.ts
lib/javascript/fullstack_demo/vitest.config.mts

chore: introduces a prisma client fake for demo purposes

---

lib/javascript/fullstack_demo/src/components/todo-app/todo-app.spec.tsx

chore: refactors tests
